package workoutmanager.applet;

import java.awt.Container;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.net.URL;

import workoutmanager.database.XMLReader;

/**
 * A LoginView is a simple Login screen. Does not contain: Register user
 * function.
 * 
 * @author Helson
 */
public class LoginView extends AbstractView {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private boolean login_sucess = false;
	
	/**
	 * Creates new LoginView.
	 */
	public LoginView(ViewManager manager, Container container) {
		super(manager, container);
		initComponents();
		container.add(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		userNameLabel = new javax.swing.JLabel();
		passwordLabel = new javax.swing.JLabel();
		usernameField = new javax.swing.JTextField();
		passwordField = new javax.swing.JPasswordField();
		submitButton = new javax.swing.JButton();
		loginSucess = new javax.swing.JLabel();
		
		java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
		layout.columnWidths = new int[] { 0, 7, 0, 7, 0, 7, 0 };
		layout.rowHeights = new int[] { 0, 7, 0, 7, 0, 7, 0, 7, 0 };
		setLayout(layout);

		userNameLabel.setText("Username:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		add(userNameLabel, gridBagConstraints);

		passwordLabel.setText("Password:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		add(passwordLabel, gridBagConstraints);
		
		loginSucess.setText(" ");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		add(loginSucess, gridBagConstraints);
		
		usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				usernameFieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(usernameField, gridBagConstraints);

		passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				passwordFieldKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(passwordField, gridBagConstraints);

		submitButton.setText("Login");
		submitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				submitButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 6;
		add(submitButton, gridBagConstraints);
	}

	private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			login();
		}
	}

	private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			login();
		}
	}
	
	private void login() {
		submitButton.doClick();
		if(login_sucess)
			createMainScreen();
		else
			login_failed();
		System.out.println("Login sucess: "+ login_sucess);
	}
	
	private void login_failed() {
		loginSucess.setText("Login failed.");
		repaint();
	}
	
	private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			login_sucess = XMLReader.read2(
					new URL(getDataBaseURL(usernameField.getText(),
							passwordField.getPassword())), "status");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}
	
	private String getDataBaseURL(String username, String password) {
		return "http://carlunger.se/login.php?username=" + username
				+ "&password=" + password + "";
	}

	private String getDataBaseURL(String username, char[] password) {
		return getDataBaseURL(username, String.copyValueOf(password));
	}
	
	private void createMainScreen() {
		ViewManager.get().addView(new MainView(getManager(), getParent()));
		remove();
	}
	
	// Variables declaration
	private javax.swing.JPasswordField passwordField;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JButton submitButton;
	private javax.swing.JLabel userNameLabel;
	private javax.swing.JTextField usernameField;
	private javax.swing.JLabel loginSucess;
	// End of variables declaration
}
