package workoutmanager.applet;

import java.awt.Container;
import java.awt.event.KeyEvent;

/**
 *
 * @author Helson
 */
public class LoginView extends java.awt.Panel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewPanel
     */
    public LoginView(Container container) {
    	this.container = container;
        initComponents();
        container.add(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0};
        layout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0};
        setLayout(layout);

        userNameLabel.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(userNameLabel, gridBagConstraints);

        passwordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(passwordLabel, gridBagConstraints);

        usernameField.setText("");
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(usernameField, gridBagConstraints);

        passwordField.setText("");
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(passwordField, gridBagConstraints);

        submitButton.setText("Login");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        add(submitButton, gridBagConstraints);
    }// </editor-fold>

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {                                         
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submitButton.doClick();
        }
    }                                        

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {                                         
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submitButton.doClick();
        }
    }                                        

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println("Hello");
    }                                            

    // Variables declaration
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameField;
    private java.awt.Container container;
    // End of variables declaration
}
